// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQc_Y0IIGCTaeQV7cTCxmJkAKCAgXvHwg',
    appId: '1:773141981676:web:d511f21d3a1713da1578c9',
    messagingSenderId: '773141981676',
    projectId: 'time-table-ac7a3',
    authDomain: 'time-table-ac7a3.firebaseapp.com',
    storageBucket: 'time-table-ac7a3.firebasestorage.app',
    measurementId: 'G-H7VCSY0RNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbvX1Lp9zfP_macePPjFKLNeEEJ4u52VY',
    appId: '1:773141981676:android:c316fc3a43644aca1578c9',
    messagingSenderId: '773141981676',
    projectId: 'time-table-ac7a3',
    storageBucket: 'time-table-ac7a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzeqXihEPqhLk93NSGSbV4INVWqDY8yhg',
    appId: '1:773141981676:ios:c87942cea4a534a81578c9',
    messagingSenderId: '773141981676',
    projectId: 'time-table-ac7a3',
    storageBucket: 'time-table-ac7a3.firebasestorage.app',
    iosBundleId: 'com.example.timeTable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzeqXihEPqhLk93NSGSbV4INVWqDY8yhg',
    appId: '1:773141981676:ios:c87942cea4a534a81578c9',
    messagingSenderId: '773141981676',
    projectId: 'time-table-ac7a3',
    storageBucket: 'time-table-ac7a3.firebasestorage.app',
    iosBundleId: 'com.example.timeTable',
  );
}
